### ISSUE TITLE
Unable to register user

### ISSUE THREAD

**Issue by girishalgundi** [AslamThachapalli/face-authentication-app#3] opened 2023-12-11 05:31 UTC
Hi Aslam,
I am trying to register user on button click I am not able to register the user, can you check quickly 

error log >>

D/ViewRootImpl@32ca51d[MainActivity](24930): ViewPostImeInputStage processPointer 0
D/ViewRootImpl@32ca51d[MainActivity](24930): ViewPostImeInputStage processPointer 1
E/flutter (24930): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (24930): #0      EnterPasswordView.build.<anonymous closure>.<anonymous closure> (package:face_auth/register_face/enter_password_view.dart:59:74)
E/flutter (24930): #1      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:846:45)
E/flutter (24930): #2      Future._propagateToListeners (dart:async/future_impl.dart:875:13)
E/flutter (24930): #3      Future._completeWithValue (dart:async/future_impl.dart:647:5)
E/flutter (24930): <asynchronous suspension>
E/flutter (24930):

**Comment by AslamThachapalli** [comment] 2023-12-27 06:58
Hi @girishalgundi ,
Are you still facing this issue?

I think the issue is from firebase.

Check if you have done the following steps after registering the app in firebase:
1. In **Firestore Database** create a collection named **password**
2. Add a document with fields *id* and *password* and add a password of your liking in it.
3. Then restart the app. 

- In the enter password screen, the password you entered is validated from the password you just entered in firebase. 
- The app is missing this data while validating. This can be the issue. 

#### Refer this image
![face auth firestore snap](https://github.com/AslamThachapalli/face-authentication-app/assets/113328135/bacafb89-8deb-47b0-a800-201d87808505)

My bad, I should have added these steps in the Readme file. I will update the Readme with the required steps. Thanks for letting it to my attention.

Try this and let me know.

**Comment by AslamThachapalli** [comment] 2024-04-26 19:26
Hope this steps solves the Error.

Closing the issue.

**Closed as completed by AslamThachapalli** 2024-04-26 19:26 UTC

**Comment by BhavishyaBhojwani** [comment] 2024-05-14 11:27
Step 1: Open the "enter_password_view.dart" file, and replace your current document ID with the old one to resolve the issue of not registering the face. #3 solved!
